### ISSUE TITLE
Fix SyntaxError in Louie 2.0

### ISSUE THREAD

**Issue by shailthacker** [11craft/louie#11]
- Louie PyPI link [https://pypi.org/project/Louie/](url)
- Installation command: `pip install Louie`

- Try to install latest Louie from above description, but failed to install. Received following error

> ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-QL6cz7/Louie/setup.py", line 3, in <module>
        from louie import version
      File "louie/__init__.py", line 1, in <module>
        from . import dispatcher, error, plugin, robustapply, saferef, sender, signal, version
      File "louie/dispatcher.py", line 44
        f"Louie connects: {connects}\n"
        ^
    SyntaxError: invalid syntax

**Comment by gldnspud** [comment]
Which version of Python are you using?

The 2.0 release of Louie supports Python 3.6 or later, which is when [f-strings](https://www.python.org/dev/peps/pep-0498/) were introduced.

If you are using Python 3.5, I would be willing to release a 2.0.1 version that reverts back to the `str.format()` style of string interpolation.

Anything 3.4 and earlier has been [end-of-lifed](https://devguide.python.org/devcycle/#end-of-life-branches) and 2.7 is being [sunsetted Jan 1 2020](https://www.python.org/doc/sunset-python-2/) so will no longer be tested against.
